apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::194722402815:role/EKSIAMAdminAccessRole
      username: admin
      groups:
        - system:masters
        - admin-users
    - rolearn: arn:aws:iam::194722402815:role/eksctl-2403-g1-pin-final-nodegroup-NodeInstanceRole-1dmqIhuZob5D
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    # Se recomienda evitar mapear usuarios individuales en producción.
