name: Terraform Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código del repositorio
        uses: actions/checkout@v2

      - name: Configurar credenciales AWS desde GitHub Secrets
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Inicializar Terraform
        run: cd terraform && terraform init

      - name: Plan de Terraform
        run: cd terraform && terraform plan

      - name: Aplicar cambios con Terraform
        run: cd terraform && terraform apply -auto-approve
