apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "50m"     # Solicita 50 milicores de CPU
          memory: "64Mi" # Solicita 64 MiB de RAM
        limits:
          cpu: "100m"     # Límite de 100 milicores de CPU
          memory: "128Mi" # Límite de 128 MiB de RAM

