apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: __namespace__
spec:
  type: LoadBalancer
  ports:
    - port: 80        # Puerto que se expondrá públicamente
      targetPort: 80  # Puerto del contenedor
  selector:
    app: nginx      # Selecciona los pods con la etiqueta "app: nginx"